spring.profiles.active=@spring.profiles.active@

server.port=8081
spring.application.name=event-service

app.storage.location=content-dir
app.jwt.secret=8fhgeigayuf64oq8ltw36pi84wl87trf8afpw7ty934t7fwaeGTFyugfldlsjfdglja
app.invitation.send.attempts-count=2

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=eventmanager586@gmail.com
spring.mail.password=zpbyrzagwjfjsgfr
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true